services:

  app:
    build:
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - .:/app
    restart: on-failure
    container_name: ddash_api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:16.2-alpine
    restart: unless-stopped
    container_name: ddash_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    env_file: '.env'
    environment:
      POSTGRES_DB: ddash
      POSTGRES_USER: ddash
      POSTGRES_PASSWORD: ddash
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres/:/var/lib/postgres/data/
