"""add_is_active_field_to_organization_membership

Revision ID: 7b46cf3e1609
Revises: 3cb889c8d8c3
Create Date: 2024-12-09 18:38:41.849033+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7b46cf3e1609"
down_revision: Union[str, None] = "3cb889c8d8c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organization_memberships", sa.Column("is_active", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organization_memberships", "is_active")
    # ### end Alembic commands ###
