"""add_name_fields_to_user

Revision ID: 3cb889c8d8c3
Revises: 2997e46a35a6
Create Date: 2024-12-08 16:33:31.820832+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cb889c8d8c3"
down_revision: Union[str, None] = "2997e46a35a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "users", sa.Column("display_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "display_name")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
